[CU-86b2ek73b] Add transformations cmds
DNAstack/dnastack-client pull request #39
Opened 2024-10-17 03:03 UTC by mpanik

2024-10-17 03:03 UTC, platform-automation-dnastack commented
Task linked: [CU-86b2ek73b Add CLI commands to interact with transformations](https://app.clickup.com/t/86b2ek73b)

2024-10-17 03:07 UTC, patmagee commented on dnastack/alpha/cli/workbench/transformations_commands.py
> +                                script: str,
I feel like here it makes sense to load the script from a file instead of allowing the user to specify it as a string directly

2024-10-17 19:23 UTC, patmagee requested changes
Tests pass and this seems to work good, I think it would be nice if we allowed the test cases to be individually runnable to make our lives / debugging easier

2024-10-17 19:23 UTC, patmagee commented on dnastack/alpha/cli/workbench/transformations_commands.py
> +                     transformation_id: str):
conventionally we allow users to describe one or more items at a time and we return the array of items

2024-10-17 19:23 UTC, patmagee commented on dnastack/alpha/cli/workbench/transformations_commands.py
> +        click.echo("Public transformations can be deleted only by admin.")
> Public transformations can be deleted only by admin.

Maybe something more generic: You are not allowed to delete public transformations

2024-10-17 19:23 UTC, patmagee commented on tests/cli/test_workbench.py
> +    def test_workflow_transformations(self):
one thing I do not like about this approach is that each individual test case is not separately testable but you need to call the parent test_workflow_transformation.

For the defaults API I actually made all of the test cases first class tests and then just moved the helper functions to the class level

2024-10-18 14:50 UTC, patmagee requested changes
@mpanik it seems there is an issue in one of the tests. ONce that it is fixed this would be really good

```
[Endpoint] ● UPDATE ewes-service (com.dnastack.workbench:ewes-service:1.0.0) at https://api.workbench.beta.dnastack.com
[Endpoint] ● UPDATE sample-user-service (com.dnastack.workbench:sample-service:1.0.0) at https://api.workbench.beta.dnastack.com
[Endpoint] o KEEP workbench-frontend.beta.dnastack.com (org.ga4gh:service-registry:1.0.0) at https://workbench-frontend.beta.dnastack.com/api/service-registry/
[Endpoint] ● UPDATE workbench-user-service (com.dnastack.workbench:workbench-user-service:1.0.0) at https://api.workbench.beta.dnastack.com
[Endpoint] ● UPDATE workflow-service (com.dnastack.workbench:workflow-service:1.0.0) at https://api.workbench.beta.dnastack.com
[Endpoint] ● UPDATE ewes-service (com.dnastack.workbench:ewes-service:1.0.0) at https://api.workbench.beta.dnastack.com
[Endpoint] ● UPDATE sample-user-service (com.dnastack.workbench:sample-service:1.0.0) at https://api.workbench.beta.dnastack.com
[Endpoint] o KEEP workbench-frontend.beta.dnastack.com (org.ga4gh:service-registry:1.0.0) at https://workbench-frontend.beta.dnastack.com/api/service-registry/
[Endpoint] ● UPDATE workbench-user-service (com.dnastack.workbench:workbench-user-service:1.0.0) at https://api.workbench.beta.dnastack.com
[Endpoint] ● UPDATE workflow-service (com.dnastack.workbench:workflow-service:1.0.0) at https://api.workbench.beta.dnastack.com

Error
Traceback (most recent call last):
  File "/Users/patrickmagee/development/dnastack/dnastack-client/tests/cli/test_workbench.py", line 1403, in test_workflow_transformation_describe
    transformation = WorkflowTransformation(**self.simple_invoke(
TypeError: dnastack.alpha.client.workbench.workflow.models.WorkflowTransformation() argument after ** must be a mapping, not list

```

2024-10-18 17:52 UTC, patmagee approved these changes
LGTM!

2024-10-18 18:00 UTC, merged