[CU-86b2kxqtq] Added commands to add and update gcp storage account.
DNAstack/dnastack-client pull request #46
Opened 2024-10-29 19:48 UTC by tianning-zhang

2024-10-29 19:48 UTC, platform-automation-dnastack commented
Task linked: [CU-86b2kxqtq Add add and update commands for GCP storage account](https://app.clickup.com/t/86b2kxqtq)

2024-10-30 13:58 UTC, patmagee requested changes

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +                 arg_names=['--service-account-json'],
Can you change this to be just `--service-account`

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +                 help='An human readable name for the storage account',
"A human readable name for the storage account"

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +        click.echo(style("Error: Malformed service account JSON.", fg='red'), err=True, color=True)
change to: "Error: Malformed service account"

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +        exit(1)
this is unnecessary since it is handled by the click framework

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +    """Create a new GCP storage account"""
This should be beneath the method definition

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +                 arg_names=['--service-account-json'],
^^ same as above, just --service-acount

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +
Let's move this to a helper function.

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +        exit(1)
Remove

2024-10-30 13:58 UTC, patmagee commented on dnastack/cli/workbench/storage_commands.py
> +    """Update an existing GCP storage account"""
This should also be under the method definition

2024-10-30 13:58 UTC, patmagee commented on tests/cli/test_workbench.py
> +        service_account_json = '{"type": "service_account", "project_id": "test-project"}'
this will fail without using a real service account JSON. We may need to use an env var pointing to the SA json to test with

2024-10-30 13:58 UTC, patmagee commented on tests/cli/test_workbench.py
> +        namespace = 'test-namespace'
you do not need to define the namespace, that will be handled by the cli

2024-10-30 13:58 UTC, patmagee commented on tests/cli/test_workbench.py
> +        storage_id = 'test-storage-id'
this should be randomized to avoid issues

2024-10-30 13:58 UTC, patmagee commented on tests/cli/test_workbench.py
> +        project_id = 'test-project'
These also should be drawn from env vars

2024-10-30 13:58 UTC, patmagee commented on tests/cli/test_workbench.py
> +        project_id = 'updated-test-project'
See comments above around the use of Env vars here

2024-10-31 13:56 UTC, patmagee approved these changes
LGTM!

2024-10-31 15:17 UTC, merged